CREATE TABLESPACE my_tbs
DATAFILE '/home/oracle/app/oracle/oradata/ORCL/my_tbs01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE USER covey IDENTIFIED BY welcome1
DEFAULT TABLESPACE my_tbs
QUOTA 50M ON my_tbs;

GRANT CREATE SESSION, CREATE TABLE TO covey;

ALTER DATABASE DATAFILE '/home/oracle/app/oracle/oradata/ORCL/my_tbs01.dbf'
RESIZE 200M;

ALTER TABLESPACE my_tbs
ADD DATAFILE '/home/oracle/app/oracle/oradata/ORCL/my_tbs02.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

ALTER TABLESPACE my_tbs OFFLINE;
ALTER TABLESPACE my_tbs ONLINE;

